import express from 'express';
import adminAuth from '@/middlewares/admin-auth';
import adminPasswordGate from '@/middlewares/admin-password-gate';
import { requireAdminPermission } from '@/middlewares/admin-permission';
import { requireAdminIdempotency } from '@/middlewares/admin-idempotency';
import validateRequest from '@/middlewares/validate-request';
import GameAdminController from './game-admin.controller';
import { approvalParamSchema, cancelRoundSchema, configParamSchema, createGreedyConfigSchema } from './game-admin.validation';
import GreedyAdminOpsRoutes from './greedy-admin-ops.routes';

export const GameAdminRoutes = express.Router();
GameAdminRoutes.use(adminAuth, adminPasswordGate);
GameAdminRoutes.get('/greedy/runtime', requireAdminPermission('game.read'), GameAdminController.getRuntime);
GameAdminRoutes.get('/greedy/config-versions', requireAdminPermission('game.read'), GameAdminController.listConfigs);
GameAdminRoutes.post('/greedy/config-versions/validate', requireAdminPermission('game.config.draft.create'), validateRequest(createGreedyConfigSchema), GameAdminController.validateConfig);
GameAdminRoutes.post('/greedy/config-versions', requireAdminPermission('game.config.draft.create'), requireAdminIdempotency('greedy.config.create'), validateRequest(createGreedyConfigSchema), GameAdminController.createConfig);
GameAdminRoutes.post('/greedy/config-versions/:config_id/publish', requireAdminPermission('game.config.publish'), requireAdminIdempotency('greedy.config.publish'), validateRequest(configParamSchema), GameAdminController.publishConfig);
GameAdminRoutes.post('/greedy/config-versions/:config_id/publish-request', requireAdminPermission('game.config.publish'), requireAdminIdempotency('greedy.config.publish.request'), validateRequest(configParamSchema), GameAdminController.requestPublishConfig);
GameAdminRoutes.post('/greedy/config-versions/publish-approved', requireAdminPermission('game.config.publish'), requireAdminIdempotency('greedy.config.publish.apply'), validateRequest(approvalParamSchema), GameAdminController.publishApprovedConfig);
GameAdminRoutes.post('/greedy/resume', requireAdminPermission('game.runtime.control'), requireAdminIdempotency('greedy.resume'), GameAdminController.resume);
GameAdminRoutes.post('/greedy/pause', requireAdminPermission('game.runtime.control'), requireAdminIdempotency('greedy.pause'), GameAdminController.pause);
GameAdminRoutes.post('/greedy/cancel-current-round', requireAdminPermission('round.cancel'), requireAdminIdempotency('greedy.round.cancel'), validateRequest(cancelRoundSchema), GameAdminController.cancelCurrentRound);
GameAdminRoutes.use('/greedy', GreedyAdminOpsRoutes);
